### ISSUE TITLE
Valence 0.2.0 Roadmap

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#288]
# Roadmap

Here are some things that should happen before Valence 0.2.0 is released. Not all of these are extracted into issues yet, but they could be with some added detail.

## Things to do, roughly in this order:
- [ ] Redesign player list. Make every entry an entity.
- [ ] Reimplement client self-exclusion. Don't send packets for the client's own entity.
- [ ] Divide `McEntity` into smaller components, closing #199.
- [ ] #269
- [ ] Clean up `valence_nbt` API. Make things consistent between binary and snbt.
- [ ] Add proper bounds checks to `valence_protocol`. Fix inconsistencies with the yarn mappings.
- [ ] Implement size limits while decoding binary NBT.
- [ ] Move block entities and chunks into the ECS `World`.
- [ ] Consider adding `#[derive(Reflect)]` to things in `valence_protocol` and possibly elsewhere. Put it behind a feature flag.
- [ ] Think about making valence more data-driven. Allow new blocks to be added at runtime. This would fix the poor compile times of `valence_protocol`.
- [ ] #256
- [ ] Redesign text API.
- [ ] Proper validation for serverbound inventory packets.
- [ ] Examples: Quality over quantity. Don't make an example for every piece of functionality. Make a complete minigame example demonstrating bevy states and a variety of valence features.
- [ ] Make website. Consider using Zola instead of Docusaurus (no javascript dev environments please).
- [ ] Document everything.
- [ ] Create getting started guide. Add it to the website.

## Some other things to look into, but are not strictly necessary for 0.2 (unordered):
- [ ] Consider allowing for multiple player lists instead of a single global list.
- [ ] Implement visibility system. Allow some entities to be visible only to certain clients. After #269.
- [ ] Serialization support for anvil worlds.
- [ ] Serializing and deserializing entities in anvil worlds?
- [ ] Reduce the frequency of sent entity movement updates using a configured component?
- [ ] Some entities disappearing in cow sphere example? Extract this into issue?
- [ ] Set up nix dev env. Is #9 sufficient?
- [ ] #42
- [ ] #282
- [ ] #4
- [ ] #210
- [ ] #104, after block entities and chunks are ECS entities.
- [ ] Command API.
- [ ] Implement most of the block placement rules, closing #115 and making the building example mostly complete. Consider if valence should have first-class support for placement.
- [ ] Figure out how to improve the performance of the terrain example.
- [ ] Fill in miscellaneous missing abstractions for the protocol.

**Comment by PonasKovas** [comment]
>  Redesign text API.

What specifically needs to be changed?
